# Docker Build and Push

name: Docker Build and Push

on:
  push:
    branches: [ master ]
  pull_request:

permissions:
  contents: read
  packages: write

jobs:
  build_api_container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: d.wplr.rocks
          username: ${{ secrets.REG_USER }}
          password: ${{ secrets.REG_PW }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Api image
        uses: docker/build-push-action@v6
        with:
          context: api/.
          push: true
          tags: |
            d.wplr.rocks/speakerwindows:api-${{ github.sha }}
            d.wplr.rocks/speakerwindows:api-latest
            ghcr.io/${{ github.repository_owner }}/speakerwindows:api-${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/speakerwindows:api-latest

  build_frontend_container:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: d.wplr.rocks
          username: ${{ secrets.REG_USER }}
          password: ${{ secrets.REG_PW }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Echo public API
        run: echo "NEXT_PUBLIC_HOST_URL=https://sw-api.wplr.rocks" > frontend/.env.local

      - name: Build and push Frontend image
        uses: docker/build-push-action@v6
        with:
          context: frontend/.
          push: true
          tags: |
            d.wplr.rocks/speakerwindows:frontend-${{ github.sha }}
            d.wplr.rocks/speakerwindows:frontend-latest
            ghcr.io/${{ github.repository_owner }}/speakerwindows:frontend-${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/speakerwindows:frontend-latest

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production
    needs: [build_api_container, build_frontend_container]
    if: github.event_name == 'push'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Updating API
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: kubedeploy
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: kubectl --namespace web set image deployment/speakerwindows-api api=${{ env.REGISTRY }}/${{ env.REPOSITORY }}:api-${{ github.sha }}

      - name: Updating Frontend
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: kubedeploy
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: kubectl --namespace web set image deployment/speakerwindows-frontend frontend=${{ env.REGISTRY }}/${{ env.REPOSITORY }}:frontend-${{ github.sha }}
